### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by lome** [TooTallNate/node-spotify-web#102]
Has anybody experienced connection issues recently?
Here is what I get after successfully loggin in:

```
  spotify-web POST "https://play.spotify.com/xhr/json/auth.php" +0ms
  spotify-web auth 200 status code, "application/json; charset=utf-8" content-type +861ms
  spotify-web ap resolver {"hostname":"apresolve.spotify.com","site":null,"override":null} +1ms
  spotify-web GET "http://apresolve.spotify.com" +0ms
  spotify-web ap resolver 200 status code, "application/json; charset=utf-8" content-type +742ms
  spotify-web WS "wss://lon2-linkap-a5.ap.spotify.com:443/" +4ms
  spotify-web WebSocket "open" event +1s
  spotify-web connect() +0ms
  spotify-web sendCommand("connect", [...]) +0ms
  spotify-web storing callback function for message id 0 +1ms
  spotify-web sending command: {"name":"connect","id":"0","args":[..]} +0ms
  spotify-web WebSocket "message" event: {"id":0,"result":"ok"} +227ms
  spotify-web starting heartbeat every 180 seconds +1ms
  spotify-web WebSocket "message" event: {"message":["do_work","var t2; try{ var d=new Date(); t2=d[(35725129862..toString(36<<0))[0]];}catch(_) {};this.reply('' + t2);"]} +2ms
spotify-web got "do_work" payload: "var t2; try{ var d=new Date(); t2=d[(35725129862..toString(36<<0))[0]];}catch(_) {};this.reply('' + t2);" +0ms
  spotify-web reply(["undefined"]) +1ms
  spotify-web sendCommand("sp/work_done", ["undefined"]) +0ms
  spotify-web storing callback function for message id 1 +0ms
  spotify-web sending command: {"name":"sp/work_done","id":"1","args":["undefined"]} +0ms
  spotify-web WebSocket "message" event: {"message":["ping_flash2","145 46 160 145 146 206 188 171 82 230 119 80 20 244 126 60 21 215 69 147"]} +3ms

{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

Error: connect ECONNREFUSED
  at errnoException (net.js:901:11)
  at Object.afterConnect [as oncomplete] (net.js:892:19)

```

**Comment by Zazama** [comment]
I can't login since today :/

**Comment by TooTallNate** [comment]
@1994rstefan I think your http://ping-pong.spotify.nodestuff.net service is down :frowning:

**Comment by ChrisMcKenzie** [comment]
:+1: me either

**Comment by Zazama** [comment]
@TooTallNate Are you sure it's because of the ping-pong server? I ran his server on my computer and connected it with the spotify.js but I still can't login

**Comment by ChrisMcKenzie** [comment]
@Zazama beat me to the punch, was going to say the same thing!

**Comment by TooTallNate** [comment]
Well that's definitely what the error log above is from. I haven't tried running the server manually.

**Comment by rckclmbr** [comment]
Tried running the server manually, it doesn't crash.  But i'm never getting the "login_complete" event in spotify-web.

**Comment by 1994rstefan** [comment]
Sorry for the long delay - my server is running again now.
I dont know why it was down, looks like there just crashed something...

Hope it works again now
Ragards

**Comment by giacecco** [comment]
Hurray! Everything's working again.

**Comment by denysvitali** [comment]
Nice! Awesome work guys!

**Comment by art0rz** [comment]
Why is a connection to your server required?

**Comment by lome** [comment]
Thank you guys!!!

**Comment by 1994rstefan** [comment]
@art0rz
node-spotify-web uses the same API to Spotify as the official Flash webplayer does. The process of logging in to spotify includes some security functions. Spotify sends a "ping" to the client (this ping is just a string that could for example look like this: 236 162 128 247 137 222 96 1 77 9 90 35 23 180 159 101 19 126 232 254). The Client (more detailed the Flash running at the client) then generates a "pong" based on the ping (the pong is also just a string, for the above mentioned ping it would be: 155 89 69 186 47 172 243 69 97 9) and sends it back to the Spotify API.
How this pong is generated is a secret and also changed in the past.

Because there is Flash required for generating this pongs I provide as solution an API for this task. My server runs a webbrowser and the Flash, using the API you can indirectly access the official function of the Spotify webplayer Flash for generating the pong.
So the reason why a connection is required is simply for generating this pong string.

You can also run your own API if you want. See https://github.com/1994rstefan/Spotify-Ping-Pong-API for more information about that.

**Comment by art0rz** [comment]
Thank you for the clarification.

Can I assume no login credentials or session cookies sent through your service?

**Comment by 1994rstefan** [comment]
No credentials are transfered, only the ping gets send.

See the sendPong function for more details: https://github.com/TooTallNate/node-spotify-web/blob/master/lib/spotify.js#L476

**Comment by Zazama** [comment]
@1994rstefan is your site down again? It's working if I set your server up locally, but not with your "http://ping-pong.spotify.nodestuff.net/" server

**Comment by 1994rstefan** [comment]
Sorry, up again.

**Comment by rckclmbr** [comment]
Would it be possible to host this server locally using slimerjs? That way it's not dependent on a central service.

**Comment by mattpker** [comment]
Not sure why slimerjs would be needed. The node-spotify-web could make a dependency for Spotify-Ping-Pong-API, then when node-spotify-web is required on your app it init's the local server and then this local server is used instead.

**Comment by mattpker** [comment]
Actually after looking into it more you have to have the worker.html page running in a browser on the server. The browser that it runs in has to support Adobe Flash, so this is probably why slimerjs or PhantomJS would not work. I'll look into it tomorrow and if I can get it working I will submit a pull request.

**Comment by LinusU** [comment]
I guess that it would be a good idea to host the api on more than one server. The client could then randomly choose one to connect to.

The best would of course be if we could reverse engineer the flash file again and just code it in javascript. But until that happens I don't think that everyone wants to run their own server since that requires running an instance of Flash and a full web browser.

**Comment by mattpker** [comment]
So I got it working with slimerjs but the problem is that it has to open a window and leave it running for it to work. So this will not work in an environment without a graphical interface. There is a tool called xvfb that will run slimerjs headless but this only works on Linux and OSX. With this API we want it to be cross-platform and not require an additional window to be open in order for it to run. I think at this point the current solution is probably the best. 

@LinusU, I agree that having multiple servers that it trys to ping-pong with would be optimal for redundancy. If anyone has any extra servers that can use towards this that would be awesome :).

**Comment by denysvitali** [comment]
I could set my vps on to provide the service :)

**Comment by rckclmbr** [comment]
Can we use xvfb where it is supported, and fallback to the service if it's
not?

**Comment by denysvitali** [comment]
![screenshot from 2015-01-29 18 35 32](https://cloud.githubusercontent.com/assets/4939519/5962667/b3c6a440-a7e5-11e4-8252-d09d6f6bd12a.png)
Tried it, but without success. Any suggestion? Firefox starts just fine, but hasn't Flash plugin in it, neither by installing Pepper Flash it works...

**Comment by 1994rstefan** [comment]
@denysvitali 
My server is running a minimal Debian Wheezy (64 Bit) and i had to install following additional packages: nodejs, xvfb, firefox and flashplugin-nonfree
(Maybe you have to enable the nonfree source list)

After creating a directory inside my home dir (~/spotify-ping-pong-api/) and cd into it and cloning the repository (so the sever.js is in the current directory) you have to run the following commands:
screen nodejs server.js
// exit screen with pressing strg+a and then d
screen Xvfb :0 -screen 0 1024x768x24
// exit screen with pressing strg+a and then d
DISPLAY=:0 screen firefox http://localhost:8080/worker.html

That should be enough to get it up running.

If you want to access the graphicall interface you can do so with VNC.
Install the package x11vnc, run "x11vnc -display :0" and connect to your IP via VNC.
If you close the VNC connection x11vnc will also stop, so nobody else can connect.

I am not sure if I changed any settings in Firefox via VNC, but I do not think i did.

**Comment by denysvitali** [comment]
That's why! I installed pepper flash instead of flashplugin-nonfree

Here you are:
http://vps.denv.it:1335/12-34-56-78-90-12-34-56-78-90-12-34-56-78-90-12-34-56-78-90

**Comment by sethcohn** [comment]
Back to not working again.  stopped last night.

Ran the service locally, and it works, so it's the http://ping-pong.spotify.nodestuff.net/ service down

**Comment by 1994rstefan** [comment]
Hello,

I am sorry that the service was down again.
To solve this problem for the future I have now set up two independent API-Servers.

The domain ping-pong.spotify.nodestuff.net now has two A records pointing to both of the servers, but this is not perfect because its random to which server the request is sent.

I also configured the domains 1.ping-pong.spotify.nodestuff.net and 2.ping-pong.spotify.nodestuff.net to point respectively to server one and two. It would be nice if someone could create a pull request to use the two servers in a usefull way. (Try to request server 1, if it failes, try to request server 2)

Best regards

**Comment by karroffel** [comment]
Looks like the service is down again. Tried to set up my local ping pong server and everything works, but I always get errors because I live in germany. Screw that.

**Comment by Zazama** [comment]
@ThomasHerzog I'm also from Germany using my own ping pong server without problems. I'm using node.js 0.10.36. I've had region errors when using version 0.11.\* or 0.12.*, so I just fell back to the old one.

**Comment by karroffel** [comment]
@Zazama Thank you very much! I got it running using the older node.js version!
