### ISSUE TITLE
Possible to authenticate using any of the oauth flows for the Spotify Web API?

### ISSUE THREAD

**Issue by sciencepro** [TooTallNate/node-spotify-web#99]
Is it possible to utilize any of the tokens obtained through sending a user through an oauth flow as described here: 

https://developer.spotify.com/web-api/authorization-guide/

**Comment by voronianski** [comment]
@sciencepro it looks like this is impossible, as `node-spotify-web` acts like web player and doesn't utilize Web API. 

/cc @TooTallNate

**Comment by voronianski** [comment]
@sciencepro @TooTallNate I was also thinking about using Web API in order to simplify Facebook login process in my OS X desktop application.. But it looks like I will need to play around with my own appId and Facebook SDK + https://github.com/TooTallNate/node-spotify-web/blob/master/lib/spotify.js#L176

It's the only way I suppose, am I right?

**Comment by sciencepro** [comment]
Facebook login indeed works, it's a good solution.  You don't need your own appid per #33.
